stages:
 - build

Ubuntu-Required-Deps:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_TARGETS="test"
  - export JAMBS_TARGETS="vmmlib"
  - export BUILD_GENERATOR="Unix Makefiles";
  - bash .gitlab-ci.sh
 tags:
  - ubuntu

Ubuntu-Optional-Deps:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_TARGETS="test"
  - export JAMBS_TARGETS="vmmlib;brion;lunchbox;bbpsdk"
  - export BUILD_GENERATOR="Unix Makefiles"
  - bash .gitlab-ci.sh
 tags:
  - ubuntu

Ubuntu-Subproject:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_TARGETS="test"
  - export BUILD_GENERATOR="Unix Makefiles";
  - bash .gitlab-ci.sh
 tags:
  - ubuntu

OSX-Required-Deps:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - source $ENVFILESDIR/Qt-5.4
  - export CMAKE_EXTRA_TARGETS="test"
  - export JAMBS_TARGETS="vmmlib"
  - export BUILD_GENERATOR="Unix Makefiles";
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlab-ci.sh
 tags:
  - osx

OSX-Optional-Deps:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - source $ENVFILESDIR/Qt-5.4
  - export CMAKE_EXTRA_TARGETS="test"
  - export JAMBS_TARGETS="vmmlib;brion;lunchbox;bbpsdk"
  - export BUILD_GENERATOR="Unix Makefiles"
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlab-ci.sh
 tags:
  - osx

OSX-Subproject:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - source $ENVFILESDIR/Qt-5.4
  - export CMAKE_EXTRA_TARGETS="test"
  - export BUILD_GENERATOR="Unix Makefiles";
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlab-ci.sh
 tags:
  - osx

Win7:
 stage: build
 script:
  - call %ENVFILESDIR%\Boost-1.56-vs12-x64.bat
  - call %ENVFILESDIR%\HDF5-1.8.14-vs12-x64.bat
  - set CMAKE_EXTRA_TARGETS=RUN_TESTS
  - set RUN_TESTS=1
  - set BUILD_GENERATOR=Visual Studio 12 Win64
  - set PATH=%PATH%;"c:\\Program Files (x86)\\Git\\bin"
  - bash.exe --login .gitlab-ci.sh
 tags:
  - win7
